from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .common import load_json


def _identifier(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    return cleaned if not cleaned[:1].isdigit() else f"value_{cleaned}"


def _dart_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if reference:
        return _identifier(reference.rsplit("/", 1)[-1])
    kind = schema.get("type")
    if kind == "array":
        return f"List<{_dart_type(schema.get('items', {}))}>"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "double"
    if kind == "boolean":
        return "bool"
    if kind == "object":
        return "Map<String, dynamic>"
    return "String"


def _decode_expression(name: str, schema: dict[str, Any]) -> str:
    wire = f"json['{name}']"
    dart_type = _dart_type(schema)
    if dart_type.startswith("List<"):
        inner = dart_type[5:-1]
        if "$ref" in schema.get("items", {}):
            return f"({wire} as List).map((e) => {inner}.fromJson(e as Map<String, dynamic>)).toList()"
        return f"List<{inner}>.from({wire} as List)"
    if "$ref" in schema:
        return f"{dart_type}.fromJson({wire} as Map<String, dynamic>)"
    if dart_type == "double":
        return f"({wire} as num).toDouble()"
    return f"{wire} as {dart_type}"


def generate(openapi_path: Path, output_path: Path) -> None:
    document = load_json(openapi_path)
    schemas = document.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        raise ValueError("OpenAPI document has no components.schemas")
    lines = ["// Generated by ContractForge Dart. Do not edit.", ""]
    for wire_name in sorted(schemas):
        schema = schemas[wire_name]
        if not isinstance(schema, dict) or schema.get("type") != "object":
            continue
        class_name = _identifier(wire_name)
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines.append(f"class {class_name} {{")
        for name, field in properties.items():
            nullable = "" if name in required else "?"
            lines.append(f"  final {_dart_type(field)}{nullable} {_identifier(name)};")
        lines.append("")
        parameters = ", ".join(("required " if name in required else "") + f"this.{_identifier(name)}" for name in properties)
        lines.append(f"  const {class_name}({{{parameters}}});")
        lines.append("")
        lines.append(f"  factory {class_name}.fromJson(Map<String, dynamic> json) => {class_name}(")
        for name, field in properties.items():
            expression = _decode_expression(name, field)
            if name not in required:
                expression = f"json['{name}'] == null ? null : {expression}"
            lines.append(f"    {_identifier(name)}: {expression},")
        lines.append("  );")
        lines.append("")
        lines.append("  Map<String, dynamic> toJson() => {")
        for name, field in properties.items():
            identifier = _identifier(name)
            value = identifier
            if "$ref" in field:
                value = f"{identifier}?.toJson()" if name not in required else f"{identifier}.toJson()"
            lines.append(f"    '{name}': {value},")
        lines.extend(["  };", "}", ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
